name: Backup Firestore@4

on:
  schedule:
    - cron: '40 16 * * *'

env:
  PROJECT_ID: likeyesterday-fd13b
  BUCKET: gs://backupfirestorecrontesting
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info
    - run: gcloud config set project $PROJECT_ID
    - run: gcloud firestore export $BUCKET
